### ISSUE TITLE
Would You Mind Adding these works to your paper? 

### ISSUE THREAD

**Issue by FuxiaoLiu** [PKU-Alignment/AlignmentSurvey#1]
Thanks for your interesting work! I have some papers which are quite related to your paper. Would you mind adding them?Thanks!

Our paper "[Mitigating Hallucination in Large Multi-Modal Models via Robust Instruction Tuning](https://arxiv.org/pdf/2306.14565.pdf)" (published in June) introduced GAVIE to evaluate hallucination of LLM with vision modality(cross-modality alignment), which is very related to your topic about AI alignment.

```
@article{liu2023aligning,
  title={Aligning Large Multi-Modal Model with Robust Instruction Tuning},
  author={Liu, Fuxiao and Lin, Kevin and Li, Linjie and Wang, Jianfeng and Yacoob, Yaser and Wang, Lijuan},
  journal={arXiv preprint arXiv:2306.14565},
  year={2023}
}
```

Our paper: [HallusionBench: You See What You Think? Or You Think What You See? An Image-Context Reasoning Benchmark Challenging for GPT-4V(ision), LLaVA-1.5, and Other Multi-modality Models](https://arxiv.org/abs/2310.14566) benchmark the illusion or hallucination issue of GPT-4V and LLaVA1.5. 

```
 @article{liu2023hallusionbench,
  title={HallusionBench: You See What You Think? Or You Think What You See? An Image-Context Reasoning Benchmark Challenging for GPT-4V (ision), LLaVA-1.5, and Other Multi-modality Models},
  author={Liu, Fuxiao and Guan, Tianrui and Li, Zongxia and Chen, Lichang and Yacoob, Yaser and Manocha, Dinesh and Zhou, Tianyi},
  journal={arXiv preprint arXiv:2310.14566},
  year={2023}
}
```
 
Our paper [COVID-VTS: Fact Extraction and Verification on Short Video Platforms](https://arxiv.org/abs/2302.07919) (EACL2023)proposed transformer-based method to align text with videos. 

```
@article{liu2023covid,
  title={COVID-VTS: Fact Extraction and Verification on Short Video Platforms},
  author={Liu, Fuxiao and Yacoob, Yaser and Shrivastava, Abhinav},
  journal={arXiv preprint arXiv:2302.07919},
  year={2023}
}
```

**Comment by cby-pku** [comment]
We are glad that you liked our survey.

We appreciate your suggestion to incorporate GAVIE\HallusionBench\COVID-VTS into the survey, and we agree that it is something to be covered. We will further read them and try to include them in our next version!

Thanks again! Suggestions help us improve our work.
